# This code snippet contains only GUI design part.

from tkinter import *

root = Tk()
root.title("BIO-DATA")

lbl1 = Label(root, text="PERSONAL INFO.")
lbl2 = Label(root, text="Last name")
lbl3 = Label(root, text="middle name")
lbl4 = Label(root, text=" Father name")
lbl5 = Label(root, text="NAME")
lbl6 = Label(root, text="ADDERESS")
lbl7 = Label(root, text="Age")
lbl8 = Label(root, text="Sex")
lbl9 = Label(root, text="Weight")
lbl10 = Label(root, text="Height")
lbl11 = Label(root, text="Blood gr.")
lbl12 = Label(root, text="Hobby")
lbl13 = Label(root, text="Contact no.")
lbl14 = Label(root, text="EDUCATIONAL INFO.")
lbl15 = Label(root, text="College name")
lbl16 = Label(root, text="Stream")
lbl17 = Label(root, text="STD")
lbl18 = Label(root, text="Roll no.")
btn = Button(root, text="SUBMIT")

e1 = Entry(root)
e2 = Entry(root)
e3 = Entry(root)
e4 = Entry(root)
e5 = Entry(root)
e6 = Entry(root)
e7 = Entry(root)
e8 = Entry(root)
e9 = Entry(root)
e10 = Entry(root)
e11 = Entry(root)
e12 = Entry(root)
e13 = Entry(root)
e14 = Entry(root)
e15 = Entry(root)

lbl1.grid(columnspan=2)
lbl2.grid(row=1, column=1)
lbl3.grid(row=1, column=2)
lbl4.grid(row=1, column=3)
lbl5.grid(row=2, column=0)
lbl6.grid(row=3, column=0)
lbl7.grid(row=4, column=0)
lbl8.grid(row=4, column=2)
lbl9.grid(row=5, column=0)
lbl10.grid(row=5, column=2)
lbl11.grid(row=6, column=0)
lbl12.grid(row=6, column=2)
lbl13.grid(row=7, column=0)
lbl14.grid(columnspan=2)
lbl15.grid(row=9, column=0)
lbl16.grid(row=10, column=0)
lbl17.grid(row=11, column=0)
lbl18.grid(row=12, column=0)

e1.grid(row=2, column=1)
e2.grid(row=2, column=2)
e3.grid(row=2, column=3)
e4.grid(row=3, column=1)
e5.grid(row=4, column=1)
e6.grid(row=4, column=3)
e7.grid(row=5, column=1)
e8.grid(row=5, column=3)
e9.grid(row=6, column=1)
e10.grid(row=6, column=3)
e11.grid(row=7, column=1)
e12.grid(row=9, column=1)
e13.grid(row=10, column=1)
e14.grid(row=11, column=1)
e15.grid(row=12, column=1)

btn.grid(columnspan=2)

root.mainloop()
