from tkinter import *

root = Tk()
root.title("PROFILE")

lbl1 = Label(root, text="Name")
lbl2 = Label(root, text="Subject")
lbl3 = Label(root, text="Year")
lbl4 = Label(root, text="Sem")
lbl5 = Label(root, text="Class")
lbl6 = Label(root, text="Roll no.")
lbl7 = Label(root, text="Academic Year")
lbl8 = Label(root, text="Professor in charge")
lbl9 = Label(root, text="Department")
lbl10 = Label(root, text="HOD")
lbl11 = Label(root, text="University")

btn = Button(root, text="SUBMIT")
btn.grid(row=7, column=0)

lbl1.grid(row=0, column=0)
lbl2.grid(row=1, column=0)
lbl3.grid(row=2, column=0)
lbl4.grid(row=2, column=2)
lbl5.grid(row=3, column=0)
lbl6.grid(row=3, column=2)
lbl7.grid(row=4, column=0)
lbl8.grid(row=5, column=0)
lbl9.grid(row=6, column=0)
lbl10.grid(row=6, column=2)
lbl11.grid(row=7, column=0)

e1 = Entry(root)
e2 = Entry(root)
e3 = Entry(root)
e4 = Entry(root)
e5 = Entry(root)
e6 = Entry(root)
e7 = Entry(root)
e8 = Entry(root)
e9 = Entry(root)
e10 = Entry(root)
e11 = Entry(root)

e1.grid(row=0, column=1)
e2.grid(row=1, column=1)
e3.grid(row=2, column=1)
e4.grid(row=2, column=3)
e5.grid(row=3, column=1)
e6.grid(row=3, column=3)
e7.grid(row=4, column=1)
e8.grid(row=5, column=1)
e9.grid(row=5, column=1)
e10.grid(row=6, column=3)
e11.grid(row=6, column=6)

root.mainloop()
